# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='public_id',
            field=models.CharField(db_index=True, default=None, max_length=10, null=True),
            preserve_default=False,
        ),
    ]
