# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models

from .. import public_id


def forwards_func(apps, schema_editor):
    TestAnswer = apps.get_model("tests_app", "TestAnswer")
    for answer in TestAnswer.objects.iterator():
        answer.public_id = public_id.encode(answer.id)
        answer.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0002_testanswer_public_id'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='testanswer',
            name='public_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
            preserve_default=False,
        )
    ]
